// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetEvents() {
  return window['go']['main']['App']['GetEvents']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IgnoreDevices(arg1) {
  return window['go']['main']['App']['IgnoreDevices'](arg1);
}

export function IsMonitoring() {
  return window['go']['main']['App']['IsMonitoring']();
}

export function SetInterval(arg1) {
  return window['go']['main']['App']['SetInterval'](arg1);
}

export function StartMonitor() {
  return window['go']['main']['App']['StartMonitor']();
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}

export function TriggerSweep() {
  return window['go']['main']['App']['TriggerSweep']();
}
