// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDevices():Promise<Record<string, main.Device>>;

export function GetEvents():Promise<Array<main.Event>>;

export function GetStatus():Promise<void>;

export function IgnoreDevices(arg1:string):Promise<void>;

export function IsMonitoring():Promise<boolean>;

export function SetInterval(arg1:number):Promise<void>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;

export function TriggerSweep():Promise<void>;
